######################################################################
# PixInsight Makefile Generator Script v1.107
# Copyright (C) 2009-2018 Pleiades Astrophoto
######################################################################
# Generated on .... 2018-12-12T13:32:16.409Z
# Project id ...... BMP
# Project type .... Module
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

