######################################################################
# PixInsight Makefile Generator Script v1.105
# Copyright (C) 2009-2017 Pleiades Astrophoto
######################################################################
# Generated on .... 2017-10-12T08:12:40.330Z
# Project id ...... ArcsinhStretch
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

