#!/bin/bash
#
# Sets up the environment for PI developement.
# Consider customizing some of the names and paths

# directory that contains your clones of the github repositories.
# The scripts assume that the sub directories PCL and PJSR contain
# the clones of of the corresponding repositories
export PI_GIT_BASE=$HOME/GitHub
# your user name on GitHub, where you keep the fork you later user
# for creating pull requests
export PI_GIT_USERNAME="GeorgViehoever"
# directory that contains the Pixinsight installation
export PI_DIR=$HOME/PixInsight
# do plausibility check of paths
checkDirs () {
    if [ ! -f $PCLDIR/include/pcl/AbstractImage.h ]
    then
	echo "Warning: $PCLDIR apparently does not point to PCL installation"
    fi
    if [ ! -f $PJSRDIR/include/pjsr/ImageOp.jsh ]
    then
	echo "Warning: $PCLDIR apparently does not point to PCL installation"
	exit 1
    fi
    if [ ! -x $PI_DIR/bin/PixInsight.sh ]
    then
	echo "$PI_DIR apparently does not point to a PixInsight installation"
	exit 1
    fi
}

#
# main
#

# set environment variables for use with PCL
export PCLDIR=$PI_GIT_BASE/PCL
export PCLBINDIR64=$PCLDIR/bin 
#export PCLBINDIR32=. # obsolete
export PCLBINDIR=$PCLBINDIR64
export PCLLIBDIR64=$PCLDIR/lib/linux/x86_64
#export PCLLIBDIR32=. # obsolete
export PCLLIBDIR=$PCLLIBDIR64
export PCLINCDIR=$PCLDIR/include
export PCLSRCDIR=$PCLDIR/src

# environment variables for PJSR - mainly for use with doxygen
export PJSRDIR=$PI_GIT_BASE/PJSR
# scripts directory in product. Contains a number of scripts
# that are not contained in PJSR repository, but are nevertheless
# useful as examples
export PJSRPRODSCRIPTS=$PI_DIR/src/scripts

# environment variables for XISF spec
export XISFDIR=$PI_GIT_BASE/XISF-specification

# devtool directory. Added to PATH
export PIDEVTOOLSDIR=$PCLDIR/devTools
# output of doxygen
export PIDOXYGENDIR=$PI_GIT_BASE/doxy_html
# doxygen configuration file
export PIDOXYGENCONF=$PIDEVTOOLSDIR/piDoxygen.conf

# add utilities directory to PATH
export PATH=$PIDEVTOOLSDIR:$PI_DIR/bin:$PATH

# plausibility check
checkDirs

echo "Starting new $SHELL with environment variables set up for PCL/PJSR development."
echo "Leave shell with 'exit' command"
exec $SHELL
