#!/bin/bash
#
# Sync and merge to master from upstream. Afterwards, we are in master branch

cd $PCLDIR
git fetch upstream
git checkout master
git merge upstream/master
cd $PJSRDIR
git fetch upstream
git checkout master
git merge upstream/master

cd $XISFDIR
git fetch upstream
git checkout master
git merge upstream/master

echo "in master branch now"
