#!/bin/bash
#
# Script that will simply make everything. Since there is no central
# Makefile for PCL and associated modules, this tries to do the job
#
# Will also create the necessary directories

# pattern for identifying Makefiles
makeDir="linux/g++"
makefileName="$makeDir/Makefile"
makefilePattern="*/linux/g++/Makefile"
# directory path for built files
buildDir="x64/Release"

function makeProject()
# makes project where makefile is located in $1
{
	echo "makefile=$1"
	makefilePath=$1
	makefileDir=$(dirname $makefilePath)
	pushd $makefileDir
	mkdir -p $buildDir
	make
	popd
}

function findProjects()
# finds Makefiles in base directory given in $1
{
	baseDir=$1
	find $baseDir -path $makefilePattern
}

function makeProjects()
# makes all projects based on the list of Makefile paths given in $1
{
	makeFiles=$1
	for makefilePath in $makeFiles
	do
		makeProject $makefilePath
	done
}

function make3rdParty()
# make 3rdparty projects.
{
	# special dirs for src/3rdparty/jasper
	jasperBuildDir="src/3rdparty/jasper/$makeDir/$buildDir"
	mkdir -p $jasperBuildDir
	mkdir -p $jasperBuildDir/base
	mkdir -p $jasperBuildDir/jp2
	mkdir -p $jasperBuildDir/jpc
	# special dirs for cfitsio
	cfitsioBuildDir="src/3rdparty/cfitsio/$makeDir/$buildDir"
	mkdir -p $cfitsioBuildDir/zlib	
	# need different PCLSRCDIR
	pclSrcDirOrg=$PCLSRCDIR
	export PCLSRCDIR=$PCLSRCDIR/3rdparty
	# some are needed by others
	projects="src/3rdparty/zlib/$makefileName src/3rdparty/jpeg/$makefileName"
	makeProjects "$projects"
	projects=$(findProjects src/3rdparty)
	makeProjects "$projects"
	export PCLSRCDIR=$pclSrcDirOrg
}

function makeProcesses()
# make Processes
{
	projects=$(findProjects src/modules/processes)
	makeProjects "$projects"
	# with fedora21, the following fail:
	# - Blink: internal compiler error
	# - DrizzleIntegration: reference to ../ImageRegistration/Homography.h
	#   (not included in released sources)
}

function makeFileFormats()
# make file formats
{
	projects=$(findProjects src/modules/file-formats)
	makeProjects "$projects"
	# with fedora21, the following fail:
	# XISF due to dependency on /home/georg/GitHub/PCL/include/pcl/String.h:118:23: fatal error file not found: #  include <qglobal.h>
	#due to -D__PCL_QT_INTERFACE in makefile
}

function makeInstaller()
# make Linux installer
{
	projects=$(findProjects src/installer)
	makeProjects "$projects"	
}

function makePcl()
# make PCL library
{
	projects=$(findProjects src/pcl)
	makeProjects "$projects"
	# with fedora21, the following failes
	# - installer due to reference to ../../core/Components/Application/Version.h
}

# main
# create directory structure
cd $PCLDIR
mkdir -p $PCLLIBDIR
mkdir -p $PCLBINDIR

make3rdParty
makePcl
makeProcesses
makeFileFormats
#currently does not work
#makeInstaller

