#!/bin/bash
#
# Script that will clean all compiled files
# pattern for identifying Makefiles
makeDir="linux/g++"
makefileName="$makeDir/Makefile"
makefilePattern="*/$makefileName"


function cleanProject()
# clean project where makefile is located in $1
{
	echo "makefile=$1"
	makefilePath=$1
	makefileDir=$(dirname $makefilePath)
	pushd $makefileDir
	make clean
	popd
}

function cleanProjects()
# clean all projects based on the list of Makefile paths given in $1
{
	makeFiles=$1
	for makefilePath in $makeFiles
	do
		cleanProject $makefilePath
	done
}

function findProjects()
# finds Makefiles in base directory given in $1
{
	baseDir=$1
	find $baseDir -path $makefilePattern
}

# main
cd $PCLDIR
projects=$(findProjects src)
cleanProjects "$projects"
echo "you may also want to clean the following:"
echo ' rm $PCLBINDIR/*'
echo ' rm $PCLLIBDIR/*'



