######################################################################
# PixInsight Makefile Generator Script v1.106
# Copyright (C) 2009-2017 Pleiades Astrophoto
######################################################################
# Generated on .... 2017-11-07T09:03:10.295Z
# Project id ...... ImageIntegration
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

