######################################################################
# PixInsight Makefile Generator Script v1.108
# Copyright (C) 2009-2018 Pleiades Astrophoto
######################################################################
# Generated on .... 2018-12-26T18:51:20.275Z
# Project id ...... RAW
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

