######################################################################
# PixInsight Makefile Generator Script v1.107
# Copyright (C) 2009-2018 Pleiades Astrophoto
######################################################################
# Generated on .... 2018-11-23T18:57:59.220Z
# Project id ...... SubframeSelector
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

