######################################################################
# PixInsight Makefile Generator Script v1.104
# Copyright (C) 2009-2017 Pleiades Astrophoto
######################################################################
# Generated on .... 2017-07-18T16:09:30.373Z
# Project id ...... Debayer
# Project type .... Module
# Platform ........ Linux/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

