######################################################################
# PixInsight Makefile Generator Script v1.104
# Copyright (C) 2009-2017 Pleiades Astrophoto
######################################################################
# Generated on .... 2017-04-15T09:50:21.257Z
# Project id ...... xisf
# Project type .... Executable
# Platform ........ MacOSX/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

