######################################################################
# PixInsight Makefile Generator Script v1.109
# Copyright (C) 2009-2019 Pleiades Astrophoto
######################################################################
# Generated on .... 2019-01-21T12:08:43.813Z
# Project id ...... SubframeSelector
# Project type .... Module
# Platform ........ MacOSX/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

