######################################################################
# PixInsight Makefile Generator Script v1.104
# Copyright (C) 2009-2017 Pleiades Astrophoto
######################################################################
# Generated on .... 2017-08-01T15:57:27.408Z
# Project id ...... CosmeticCorrection
# Project type .... Module
# Platform ........ FreeBSD/g++
# Configuration ... Release/all
######################################################################

#
# Targets
#

.PHONY: all
all: 
	$(MAKE) -f ./makefile-x64 --no-print-directory

.PHONY: clean
clean:
	$(MAKE) -f ./makefile-x64 --no-print-directory clean

